# Generated by Django 3.0.6 on 2020-06-16 19:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugticket',
            name='time_filed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
