# Generated by Django 3.0.6 on 2020-06-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker_app', '0004_auto_20200628_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugticket',
            name='description',
            field=models.TextField(),
        ),
    ]
